# Generated by Django 5.1.7 on 2025-03-31 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.grupo'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.grupo'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.item'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.registro'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.item'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.registro'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='situacao',
            field=models.CharField(max_length=50),
        ),
    ]
