# Generated by Django 5.1.7 on 2025-03-31 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_receita_grupo_alter_despesa_grupo_alter_despesa_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='nome',
            field=models.CharField(default='Novo Registro', max_length=100),
        ),
    ]
