# Generated by Django 5.1.7 on 2025-03-31 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_registro_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='situacao',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('QUITADA', 'Quitada')], default='PENDENTE', max_length=10),
        ),
    ]
