# Generated by Django 5.1.7 on 2025-04-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_registro_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='prioridade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
