# Generated by Django 5.1.7 on 2025-04-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_prioridade'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='prioridade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
