# Generated by Django 5.1.7 on 2025-04-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_grupo_prioridade'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='registro',
            name='ano_ref',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='mes_ref',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
